{
  "type": "record",
  "namespace": "pe.nom.charlygastelo.app.shared.avro.dto",
  "name": "AccountUpdatedEvent",
  "fields": [
    {
      "name": "eventId",
      "type": "string"
    },
    {
      "name": "eventType",
      "type": "string",
      "default": "ACCOUNT_UPDATED"
    },
    {
      "name": "occurredAt",
      "type": "string"
    },
    {
      "name": "version",
      "type": "string",
      "default": "1.0"
    },
    {
      "name": "source",
      "type": "string",
      "default": "account-service"
    },

    {
      "name": "accountId",
      "type": "string"
    },
    {
      "name": "customerId",
      "type": "string"
    },
    {
      "name": "number",
      "type": "string"
    },
    {
      "name": "type",
      "type": "string"
    },
    {
      "name": "balance",
      "type": "double"
    },
    {
      "name": "currency",
      "type": "string"
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "active",
      "type": "boolean"
    },
    {
      "name": "updatedAt",
      "type": "string"
    }
  ]
}